permalink: /:categories/:title/
markdown: kramdown
url: "http://codeforsanfrancisco.org"
defaultbranch: master

name: Code for San Francisco
description: A volunteer civic technology group.

owner:
  twitter: sfbrigade

plugins:
  - jekyll-redirect-from

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json", "vendor", "scripts", ".travis.yml"]
